# Verbs 2: group_by and summarise


## Key takeaways

* `group_by` and `summarise` are the R equivalent to Excel's pivot tables
*  Together, they're usually used to answer questions like "how many?" and "how much?". 
*  You will rarely use `group_by` without `summarise`. 
* `group_by` is picky - it will create a separate answer for every variant of a category: "Lettuce" could be one, and "lettuce" could be another. 
* "How many?" is such a common question that there are some shortcuts for it.
*  How to roll up your answers so you can computer percent


This continues with the Arizona immunization data from chapter 4. If you've started a new project, you can [re-download the data in R form](https://github.com/cronkitedata/rstudyguide/blob/master/data/az-immunizations-grade6.Rda?raw=true), and then issue the command

    load("az-immunizations-grade6.Rda")
    
(Be sure to preface it with a subfolder name if you've saved it in one.)

## group_by / summarise^[The tidyverse uses the British spelling of a lot of words. You can use the American spelling, but you'll usually see it this way.] basics

Think of grouping as making piles of things , and summarise as adding up or counting items within the piles.  

Where filtering and selecting let you hone in on individual items that meet specific criteria, grouping and summarising help you answer the questions of "how many?" and "how much?" They're the equivalent to pivot tables in Excel. 






## Resources

* Andrew Ba Tran's "R for Journalists", bottom of chapter 3, "[Wrangling data](https://learn.r-journalism.com/en/wrangling/dplyr/dplyr/)"  
* Mary Jo Webster's "[Intro to analysis with Tidyverse](https://mjwebster.github.io/DataJ/R/IntroAnalysisWithR.html)" is a walkthrough aimed at group by / summarise.
* Go back to Pivot Tables in Excel - it's the same thing. 
* Susan Baert's dplyr tutorial: [summarizing data](https://suzan.rbind.io/2018/04/dplyr-tutorial-4/)
* Matt Waite's "[Aggregates](http://mattwaite.github.io/sports/aggregates.html)" chapter



